name: Run scraper

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule
    # https://crontab.guru/#7_2,6,10_*_*_*
    - cron:  '7 2,6,10 * * *' # UTC –> 12:00,16:00,20:00 AEST
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scrape:
    name: ⛏️ Scrape
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
        bundler-cache: true

    - name: Run scraper
      run: bundle exec ruby scrape.rb

    - name: Upload scraper database
      uses: actions/upload-artifact@v3
      with:
        name: data.sqlite
        path: data.sqlite
        if-no-files-found: error

    - name: Upload scraper database to release
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_RELEASE_SECRET }}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -H "Content-Type: application/octet-stream" \
          https://uploads.github.com/repos/auxesis/nswses_training_scraper/releases/108712870/assets?name=data.sqlite \
          --data-binary "@data.sqlite"
