name: ⛏️ Run scraper

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule
    # https://crontab.guru/#7_2,6,10_*_*_*
    - cron:  '7 2,6,10 * * *' # UTC –> 12:00,16:00,20:00 AEST
  workflow_dispatch:

permissions:
  contents: read

jobs:
  name: Scrape
  scrape:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
        bundler-cache: true
        
    - name: Run scraper
      run: bundle exec ruby scrape.rb
      
    - name: Upload scraper database
      uses: actions/upload-artifact@v3
      with:
        name: data.sqlite
        path: data.sqlite
        if-no-files-found: error 
